# Generated by Django 2.1 on 2018-09-04 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patronage", "0002_userbenefit"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemoteBenefit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remote_id", models.CharField(max_length=100, null=True)),
                ("title", models.CharField(max_length=100, null=True)),
                ("url", models.URLField(null=True)),
            ],
        ),
        migrations.RenameModel(old_name="Benefit", new_name="Tier"),
        migrations.RenameModel(old_name="UserBenefit", new_name="UserTier"),
    ]
